package com.webservices.modal;

// Generated Feb 9, 2016 1:47:48 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MyService generated by hbm2java
 */
@Entity
@Table(name = "my_service", catalog = "mysql_service")
public class DailyService implements java.io.Serializable {

	private Long id;
    private String itemDesc;	
	private Integer type;
	private Integer userId;	
	private Date createDate;
	private String active;
	private Float price;

	
	@JsonIgnore
	private Services services;

	

	public DailyService() {
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceID")
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}



	public DailyService(Date createDate, String active) {
		this.createDate = createDate;
		this.active = active;
	}


	@Column(name = "field1")
	public String getItemDesc() {
		return itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}
	@Column(name = "intfield1")
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	@Column(name = "intfield2")
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	// @JsonProperty("bill-amount")
	@Column(name = "active", nullable = false, length = 1)
	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}
  
	@Column(name = "floatfield1", precision = 12, scale = 0)
	public Float getPrice() {
		return price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	

	

}
