package com.webservices.modal;

// Generated Feb 15, 2016 12:31:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MyService generated by hbm2java
 */
@Entity
@Table(name = "my_service", catalog = "mysql_service")
public class MyService implements java.io.Serializable {

	private MyServiceId id;
	private Services services;

	public MyService() {
	}

	public MyService(MyServiceId id, Services services) {
		this.id = id;
		this.services = services;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "serviceId", column = @Column(name = "serviceID", nullable = false)),
			@AttributeOverride(name = "itemDesc", column = @Column(name = "field1")),			
			@AttributeOverride(name = "type", column = @Column(name = "intfield1")),
			@AttributeOverride(name = "userId", column = @Column(name = "intfield2")),		
			@AttributeOverride(name = "createDate", column = @Column(name = "createDate", nullable = false, length = 0)),
			@AttributeOverride(name = "active", column = @Column(name = "active", nullable = false, length = 1)),			
			@AttributeOverride(name = "price", column = @Column(name = "floatfield1", precision = 12, scale = 0)) })
	public MyServiceId getId() {
		return this.id;
	}

	public void setId(MyServiceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceID", nullable = false, insertable = false, updatable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

}
