package com.webservices.modal;

// Generated Feb 9, 2016 1:47:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceImageMappingId generated by hbm2java
 */
@Embeddable
public class ServiceImageMappingId implements java.io.Serializable {

	private int imageId;
	private int imageOrder;
	private long serviceId;

	public ServiceImageMappingId() {
	}

	public ServiceImageMappingId(int imageId, int imageOrder, long serviceId) {
		this.imageId = imageId;
		this.imageOrder = imageOrder;
		this.serviceId = serviceId;
	}

	@Column(name = "image_id", nullable = false)
	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	@Column(name = "image_order", nullable = false)
	public int getImageOrder() {
		return this.imageOrder;
	}

	public void setImageOrder(int imageOrder) {
		this.imageOrder = imageOrder;
	}

	@Column(name = "service_id", nullable = false)
	public long getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(long serviceId) {
		this.serviceId = serviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceImageMappingId))
			return false;
		ServiceImageMappingId castOther = (ServiceImageMappingId) other;

		return (this.getImageId() == castOther.getImageId())
				&& (this.getImageOrder() == castOther.getImageOrder())
				&& (this.getServiceId() == castOther.getServiceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImageId();
		result = 37 * result + this.getImageOrder();
		result = 37 * result + (int) this.getServiceId();
		return result;
	}

}
